name: Move assigned card
on:
  pull_request:
    types:
      - labeled
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: sarah
          column: Ready to work
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
