

name: Add Dependabot Pull Requests to Project Board
on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/Architect-Your-Dive/projects/1
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          labeled: dependencies
