name: Project automations
on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - labeled
jobs:
  issue_opened:
    name: issue_opened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: Move new issues to Backlog
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          organization: Architect-Your-Dive
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Backlog # Target status
  needs_investigation:
    name: needs_investigation
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled' && github.event.label.name == 'needs investigation')
    steps:
      - name: Move needs investigation labeled issues to Needs Investigation status
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          organization: Architect-Your-Dive
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Needs Investigation # Target status
  ready_to_work:
    name: ready_to_work
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && contains( github.event.pull_request.labels.*.name, 'dependencies')) ||
      (github.event.action == 'labeled' && github.event.label.name == 'approved')
    steps:
      - name: Move Dependabot PR or approved issues to Ready to work
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          organization: Architect-Your-Dive
          project_id: 1
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: Ready to Work # Target status
